#!/usr/bin/env bash

# tenv - toggle python virtual environment
#
# Copyright (c) 2018-2022, Kristofer Berggren
# All rights reserved.
#

# Application info
showusage()
{
  echo "tenv toggles enabling/disabling python virtual environment."
  echo "When environment path is not specified, it uses .env as default."
  echo "For simplest operation it is recommended setting up an alias"
  echo "for the command:"
  echo "   alias tenv=\". \`which tenv\`\""
  echo ""
  echo "Usage: . \`which tenv\`"
  echo "   or: . \`which tenv\` <path>"
  echo "   or: . \`which tenv\` OPTION"
  echo ""
  echo "Options:"
  echo "   --help         display this help and exit"
  echo "   --version      output version information and exit"
  echo ""
  echo "Report bugs at https://github.com/d99kris/tenv"
  echo ""
}

showversion()
{
  echo "tenv v1.03"
  echo ""
  echo "Copyright (C) 2018-2022 Kristofer Berggren"
  echo ""
  echo "tenv is distributed under the MIT license."
  echo ""
  echo "Written by Kristofer Berggren"
}

# Process arguments
if [[ "${1}" == "--help" ]]; then
  showusage
elif [[ "${1}" == "--version" ]]; then
  showversion
elif [[ "${1}" != "" ]]; then
  VENVPATH="${1}"
else
  VENVPATH=".env"
fi

# Toggle environment
if [[ "${VENVPATH}" != "" ]]; then
  if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    if [[ "$VIRTUAL_ENV" != "" ]]; then
      deactivate
    else
      if [[ ! -d "${VENVPATH}" ]]; then
        which virtualenv &> /dev/null
        if [[ "${?}" != "0" ]]; then
          echo "Required tool \"virtualenv\" not found."
        else
          if [[ "${TENV_NOPROMPT}" != "" ]]; then
            REPLY="y"
          else
            read -p "Directory \"${VENVPATH}\" does not exist, proceed to create it (y/n)? "
          fi
          if [[ "${REPLY}" = "y" ]]; then
            virtualenv "${VENVPATH}"
          fi
        fi
      fi

      if [[ -d "${VENVPATH}" ]]; then
        source "./${VENVPATH}/bin/activate"
      fi
    fi
  else
    showusage
    exit 1
  fi
fi
